/*
 * Copyright 2026 Amsive LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import type { ExecFileOptions } from 'node:child_process';
import path from 'node:path';
import {
	COMPILED_INCLUDE_FILENAME,
	MANAGED_MARKER_END,
	MANAGED_MARKER_START,
	ORIGIN_REQUEST_USER_AGENT,
} from './constants';
import type { NormalizedOrigin } from './types';

const MEDIA_EXTENSIONS = 'avif|bmp|gif|heic|heif|ico|jpe?g|png|svgz?|tiff?|webp';
const NGINX_COMMAND_TIMEOUT_MS = 10_000;

export interface NginxRuntimeService {
	bin: { [binaryName: string]: string } | undefined;
	configPath: string;
	runPath: string;
}

export type ExecFilePromise = (
	command: string,
	args: string[],
	options?: ExecFileOptions,
) => Promise<string>;

export type NginxReloadResult = 'reloaded' | 'restarted';

interface NginxCommandContext {
	commonArgs: string[];
	nginxBinary: string;
	options: ExecFileOptions;
}

function escapeRegularExpression(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function quoteNginx(value: string): string {
	if (/[\r\n\0]/.test(value)) {
		throw new Error('Nginx value contains an unsupported control character.');
	}

	return `"${value
		.replace(/\\/g, '\\\\')
		.replace(/"/g, '\\"')
		.replace(/\$/g, '\\$')}"`;
}

function formatProxyIp(ipAddress: string): string {
	return ipAddress.includes(':') ? `[${ipAddress}]` : ipAddress;
}

function nginxCommandContext(service: NginxRuntimeService): NginxCommandContext {
	const nginxBinary = service.bin?.nginx;
	if (!nginxBinary) {
		throw new Error('Local did not provide an Nginx binary for this site.');
	}

	const configFile = path.join(service.configPath, 'nginx.conf');
	const commonArgs = ['-c', configFile, '-p', service.runPath];
	const options: ExecFileOptions = {
		timeout: NGINX_COMMAND_TIMEOUT_MS,
		windowsHide: true,
	};

	return { commonArgs, nginxBinary, options };
}

async function validateNginxConfig(
	context: NginxCommandContext,
	execFilePromise: ExecFilePromise,
): Promise<void> {
	await execFilePromise(
		context.nginxBinary,
		['-t', ...context.commonArgs],
		context.options,
	);
}

async function signalNginxReload(
	context: NginxCommandContext,
	execFilePromise: ExecFilePromise,
): Promise<void> {
	await execFilePromise(
		context.nginxBinary,
		['-s', 'reload', ...context.commonArgs],
		context.options,
	);
}

export async function reloadNginxInPlace(
	service: NginxRuntimeService,
	execFilePromise: ExecFilePromise,
): Promise<void> {
	const context = nginxCommandContext(service);
	await validateNginxConfig(context, execFilePromise);
	await signalNginxReload(context, execFilePromise);
}

function errorOutput(error: unknown): string {
	if (!(error instanceof Error)) {
		return String(error);
	}

	const commandError = error as Error & { stderr?: unknown };
	return [
		error.message,
		typeof commandError.stderr === 'string' ? commandError.stderr : '',
	].join('\n');
}

export function isMissingNginxMasterProcess(error: unknown): boolean {
	return /kill\(\d+,\s*1\) failed \(3:\s*No such process\)/i.test(errorOutput(error));
}

export async function reloadNginxWithFallback(
	service: NginxRuntimeService,
	execFilePromise: ExecFilePromise,
	restartService: () => Promise<boolean>,
	canRestartService: () => boolean = () => true,
): Promise<NginxReloadResult> {
	const context = nginxCommandContext(service);
	await validateNginxConfig(context, execFilePromise);

	try {
		await signalNginxReload(context, execFilePromise);
		return 'reloaded';
	} catch (error) {
		if (!isMissingNginxMasterProcess(error)) {
			throw error;
		}
		if (!canRestartService()) {
			throw new Error('The Local site is no longer running; stale Nginx recovery was cancelled.');
		}

		const restarted = await restartService();
		if (!restarted) {
			throw new Error('Local did not start the Nginx service after stale-master recovery.');
		}
		return 'restarted';
	}
}

export function buildManagedNginxConfig(
	origin: NormalizedOrigin,
	trustBundlePath?: string,
): string {
	if (origin.protocol === 'https:' && !trustBundlePath) {
		throw new Error('HTTPS origins require a trusted certificate authority bundle.');
	}

	const tlsDirectives = origin.protocol === 'https:'
		? [
			'\tproxy_ssl_server_name on;',
			`\tproxy_ssl_name ${quoteNginx(origin.tlsHostname)};`,
			`\tproxy_ssl_trusted_certificate ${quoteNginx(trustBundlePath as string)};`,
			'\tproxy_ssl_verify on;',
			'\tproxy_ssl_verify_depth 5;',
		]
		: [];

	return [
		'# Generated by Local Media Proxy. Changes will be overwritten.',
		`location ~* ^/wp-content/uploads/.*\\.(?:${MEDIA_EXTENSIONS})$ {`,
		'\tif ($request_method !~ ^(GET|HEAD)$) { return 405; }',
		'\ttry_files $uri @local_media_proxy;',
		'\taccess_log off;',
		'\tlog_not_found off;',
		'\texpires 5m;',
		'\tadd_header Cache-Control "public";',
		'}',
		'',
		'location @local_media_proxy {',
		`\tproxy_pass ${origin.protocol}//${formatProxyIp(origin.originIp)}:${origin.port};`,
		`\tproxy_set_header Host ${quoteNginx(origin.hostHeader)};`,
		`\tproxy_set_header User-Agent ${quoteNginx(ORIGIN_REQUEST_USER_AGENT)};`,
		...tlsDirectives,
		'\tproxy_http_version 1.1;',
		'\tproxy_pass_request_headers off;',
		'\tproxy_pass_request_body off;',
		'\tproxy_set_header Connection "";',
		'\tproxy_set_header Content-Length "";',
		'\tproxy_set_header Authorization "";',
		'\tproxy_set_header Proxy-Authorization "";',
		'\tproxy_set_header Cookie "";',
		'\tproxy_set_header Referer "";',
		'\tproxy_set_header Origin "";',
		'\tproxy_set_header X-Forwarded-For "";',
		'\tproxy_set_header X-Forwarded-Host "";',
		'\tproxy_set_header X-Forwarded-Proto "";',
		'\tproxy_set_header Forwarded "";',
		'\tproxy_set_header X-Real-IP "";',
		'\tproxy_set_header Transfer-Encoding "";',
		'\tproxy_hide_header Set-Cookie;',
		'\tproxy_buffering off;',
		'\tproxy_request_buffering off;',
		'\tproxy_redirect off;',
		'\tproxy_intercept_errors off;',
		'\tproxy_connect_timeout 10s;',
		'\tproxy_read_timeout 60s;',
		'\tproxy_send_timeout 60s;',
		'\tadd_header X-Local-Media-Proxy "origin" always;',
		'\tadd_header X-Content-Type-Options "nosniff" always;',
		'}',
		'',
	].join('\n');
}

export function removeManagedInclude(siteConfig: string): string {
	const start = escapeRegularExpression(MANAGED_MARKER_START);
	const end = escapeRegularExpression(MANAGED_MARKER_END);
	const managedBlock = new RegExp(
		`^[\\t ]*${start}\\r?\\n[\\s\\S]*?^[\\t ]*${end}(?:\\r?\\n)?`,
		'gm',
	);

	return siteConfig.replace(managedBlock, '');
}

export function upsertManagedInclude(siteConfig: string): string {
	const eol = siteConfig.includes('\r\n') ? '\r\n' : '\n';
	const cleanConfig = removeManagedInclude(siteConfig);
	const block = [
		`    ${MANAGED_MARKER_START}`,
		`    include includes/${COMPILED_INCLUDE_FILENAME};`,
		`    ${MANAGED_MARKER_END}`,
		'',
	].join(eol);

	const wordpressComment = /^[\t ]*#[\t ]*\r?\n[\t ]*#[\t ]*WordPress Rules[\t ]*\r?\n/m;
	const firstLocation = /^[\t ]*location\b/m;
	const wordpressMatch = wordpressComment.exec(cleanConfig);
	const locationMatch = firstLocation.exec(cleanConfig);
	const anchorMatch = wordpressMatch && locationMatch
		? wordpressMatch.index <= locationMatch.index
			? wordpressMatch
			: locationMatch
		: wordpressMatch ?? locationMatch;

	if (anchorMatch?.index !== undefined) {
		return `${cleanConfig.slice(0, anchorMatch.index)}${block}${cleanConfig.slice(anchorMatch.index)}`;
	}

	const serverEnd = cleanConfig.lastIndexOf('}');
	if (serverEnd === -1) {
		throw new Error('Could not find a server block in the Local Nginx template.');
	}

	return `${cleanConfig.slice(0, serverEnd)}${eol}${block}${cleanConfig.slice(serverEnd)}`;
}

export function hasManagedInclude(siteConfig: string): boolean {
	return siteConfig.includes(MANAGED_MARKER_START) && siteConfig.includes(MANAGED_MARKER_END);
}
